package com.jpa.entities;

// Generated Jul 28, 2013 1:34:26 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Group generated by hbm2java
 */
@Entity
@Table(name = "users")
public class Group implements java.io.Serializable {

	private Long id;
	private Address address;
	private String username;
	private String password;
	private String fname;
	private String lname;
	private String email;
	private String phone;
	private Set<Groups> groupsesForGroupId = new HashSet<Groups>(0);
	private Set<Groups> groupsesForParentGroupId = new HashSet<Groups>(0);

	public Group() {
	}

	public Group(Address address, String username, String password,
			String fname, String phone) {
		this.address = address;
		this.username = username;
		this.password = password;
		this.fname = fname;
		this.phone = phone;
	}

	public Group(Address address, String username, String password,
			String fname, String lname, String email, String phone,
			Set<Groups> groupsesForGroupId, Set<Groups> groupsesForParentGroupId) {
		this.address = address;
		this.username = username;
		this.password = password;
		this.fname = fname;
		this.lname = lname;
		this.email = email;
		this.phone = phone;
		this.groupsesForGroupId = groupsesForGroupId;
		this.groupsesForParentGroupId = groupsesForParentGroupId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "fname", nullable = false, length = 100)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "lname", length = 100)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupByGroupId")
	public Set<Groups> getGroupsesForGroupId() {
		return this.groupsesForGroupId;
	}

	public void setGroupsesForGroupId(Set<Groups> groupsesForGroupId) {
		this.groupsesForGroupId = groupsesForGroupId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupByParentGroupId")
	public Set<Groups> getGroupsesForParentGroupId() {
		return this.groupsesForParentGroupId;
	}

	public void setGroupsesForParentGroupId(Set<Groups> groupsesForParentGroupId) {
		this.groupsesForParentGroupId = groupsesForParentGroupId;
	}

}
