package com.jpa.entities;

// Generated Jul 28, 2013 1:34:26 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "groups", catalog = "test")
public class Groups implements java.io.Serializable {

	private Long id;
	private Group groupByGroupId;
	private Group groupByParentGroupId;
	private int level;
	private char position;

	public Groups() {
	}

	public Groups(Group groupByGroupId, int level, char position) {
		this.groupByGroupId = groupByGroupId;
		this.level = level;
		this.position = position;
	}

	public Groups(Group groupByGroupId, Group groupByParentGroupId, int level,
			char position) {
		this.groupByGroupId = groupByGroupId;
		this.groupByParentGroupId = groupByParentGroupId;
		this.level = level;
		this.position = position;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id", nullable = false)
	public Group getGroupByGroupId() {
		return this.groupByGroupId;
	}

	public void setGroupByGroupId(Group groupByGroupId) {
		this.groupByGroupId = groupByGroupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_group_id")
	public Group getGroupByParentGroupId() {
		return this.groupByParentGroupId;
	}

	public void setGroupByParentGroupId(Group groupByParentGroupId) {
		this.groupByParentGroupId = groupByParentGroupId;
	}

	@Column(name = "level", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	@Column(name = "position", nullable = false, length = 1)
	public char getPosition() {
		return this.position;
	}

	public void setPosition(char position) {
		this.position = position;
	}

}
